<?php

namespace WalkerChiu\Core\Models\Constants;

use InvalidArgumentException;

/**
 * @license MIT
 * @package WalkerChiu\Core
 *
 * 
 */

class CountryZone
{
    /**
     * @param Int  $type
     * @return Array
     */
    public static function getCodes($type = 3): array
    {
        $items = [];
        $continents = self::all($type);
        foreach ($continents as $continent) {
            foreach ($continent as $code => $country) {
                array_push($items, $code);
            }
        }

        return $items;
    }

    /**
     * @param Int    $type
     * @param Array  $available
     * @return Array
     */
    public static function options($type = 3, $available = null): array
    {
        if (
            !is_null($available)
            && !is_array($available)
        ) {
            throw new InvalidArgumentException($available);
        }

        $items = [];
        $continents = self::all($type);
        foreach ($continents as $key => $continent) {
            $items = array_merge($items, [trans('php-core::area.'.$key) => []]);

            foreach ($continent as $code => $country) {
                if (
                    is_null($available)
                    || (
                        !empty($available)
                        && in_array($code, $available)
                    )
                ) {
                    $items[trans('php-core::area.'.$key)] = array_merge($items[trans('php-core::area.'.$key)], [$code => trans('php-core::area.'.$code)]);
                }
            }
        }

        return $items;
    }

    /**
     * @param Int  $type
     * @return Array
     */
    public static function all($type = 3): array
    {
        if ($type == 2) {
            return ['Africa' => [
                        'DZ' => 'Algeria',
                        'AO' => 'Angola',
                        'BJ' => 'Benin',
                        'BW' => 'Botswana',
                        'BF' => 'Burkina Faso',
                        'BI' => 'Burundi',
                        'CM' => 'Cameroon',
                        'CV' => 'Cape Verde',
                        'CF' => 'Central African Republic',
                        'TD' => 'Chad',
                        'KM' => 'Comoros',
                        'CG' => 'Congo',
                        'CD' => 'The Democratic Republic of The Congo',
                        'CI' => "Cote D'ivoire",
                        'DJ' => 'Djibouti',
                        'EG' => 'Egypt',
                        'GQ' => 'Equatorial Guinea',
                        'ER' => 'Eritrea',
                        'ET' => 'Ethiopia',
                        'GA' => 'Gabon',
                        'GM' => 'Gambia',
                        'GH' => 'Ghana',
                        'GN' => 'Guinea',
                        'GW' => 'Guinea-bissau',
                        'KE' => 'Kenya',
                        'LS' => 'Lesotho',
                        'LR' => 'Liberia',
                        'LY' => 'Libya',
                        'MG' => 'Madagascar',
                        'MW' => 'Malawi',
                        'ML' => 'Mali',
                        'MR' => 'Mauritania',
                        'MU' => 'Mauritius',
                        'YT' => 'Mayotte',
                        'MA' => 'Morocco',
                        'MZ' => 'Mozambique',
                        'NA' => 'Namibia',
                        'NE' => 'Niger',
                        'NG' => 'Nigeria',
                        'RE' => 'Reunion',
                        'RW' => 'Rwanda',
                        'SH' => 'Saint Helena',
                        'ST' => 'Sao Tome and Principe',
                        'SN' => 'Senegal',
                        'SC' => 'Seychelles',
                        'SL' => 'Sierra Leone',
                        'SO' => 'Somalia',
                        'ZA' => 'South Africa',
                        'SD' => 'Sudan',
                        'SS' => 'South Sudan',
                        'SZ' => 'Swaziland',
                        'TZ' => 'Tanzania',
                        'TG' => 'Togo',
                        'TN' => 'Tunisia',
                        'UG' => 'Uganda',
                        'EH' => 'Western Sahara',
                        'ZM' => 'Zambia',
                        'ZW' => 'Zimbabwe'
                    ],
                    'Antarctica' => [
                        'AQ' => 'Antarctica',
                        'BV' => 'Bouvet Island',
                        'TF' => 'French Southern Territories',
                        'HM' => 'Heard Island and Mcdonald Islands',
                        'GS' => 'South Georgia and The South Sandwich Islands'
                    ],
                    'Asia' => [
                        'AF' => 'Afghanistan',
                        'AM' => 'Armenia',
                        'AZ' => 'Azerbaijan',
                        'BH' => 'Bahrain',
                        'BD' => 'Bangladesh',
                        'BT' => 'Bhutan',
                        'IO' => 'British Indian Ocean Territory',
                        'BN' => 'Brunei Darussalam',
                        'KH' => 'Cambodia',
                        'CN' => 'China',
                        'CX' => 'Christmas Island',
                        'CC' => 'Cocos (Keeling] Islands',
                        'CY' => 'Cyprus',
                        'GE' => 'Georgia',
                        'HK' => 'Hong Kong',
                        'IN' => 'India',
                        'ID' => 'Indonesia',
                        'IR' => 'Iran',
                        'IQ' => 'Iraq',
                        'IL' => 'Israel',
                        'JP' => 'Japan',
                        'JO' => 'Jordan',
                        'KZ' => 'Kazakhstan',
                        'KP' => "Democratic People's Republic of Korea",
                        'KR' => 'Republic of Korea',
                        'KW' => 'Kuwait',
                        'KG' => 'Kyrgyzstan',
                        'LA' => "Lao People's Democratic Republic",
                        'LB' => 'Lebanon',
                        'MO' => 'Macao',
                        'MY' => 'Malaysia',
                        'MV' => 'Maldives',
                        'MN' => 'Mongolia',
                        'MM' => 'Myanmar',
                        'NP' => 'Nepal',
                        'OM' => 'Oman',
                        'PK' => 'Pakistan',
                        'PS' => 'Palestinia',
                        'PH' => 'Philippines',
                        'QA' => 'Qatar',
                        'SA' => 'Saudi Arabia',
                        'SG' => 'Singapore',
                        'LK' => 'Sri Lanka',
                        'SY' => 'Syrian Arab Republic',
                        'TW' => 'Taiwan',
                        'TJ' => 'Tajikistan',
                        'TH' => 'Thailand',
                        'TL' => 'Timor-leste',
                        'TR' => 'Turkey',
                        'TM' => 'Turkmenistan',
                        'AE' => 'United Arab Emirates',
                        'UZ' => 'Uzbekistan',
                        'VN' => 'Viet Nam',
                        'YE' => 'Yemen'
                    ],
                    'Europe' => [
                        'AX' => 'Åland Islands',
                        'AL' => 'Albania',
                        'AD' => 'Andorra',
                        'AT' => 'Austria',
                        'BY' => 'Belarus',
                        'BE' => 'Belgium',
                        'BA' => 'Bosnia and Herzegovina',
                        'BG' => 'Bulgaria',
                        'HR' => 'Croatia',
                        'CZ' => 'Czech Republic',
                        'DK' => 'Denmark',
                        'EE' => 'Estonia',
                        'FO' => 'Faroe Islands',
                        'FI' => 'Finland',
                        'FR' => 'France',
                        'DE' => 'Germany',
                        'GI' => 'Gibraltar',
                        'GR' => 'Greece',
                        'GG' => 'Guernsey',
                        'VA' => 'Holy See (Vatican City State]',
                        'HU' => 'Hungary',
                        'IS' => 'Iceland',
                        'IE' => 'Ireland',
                        'IM' => 'Isle of Man',
                        'IT' => 'Italy',
                        'JE' => 'Jersey',
                        'LV' => 'Latvia',
                        'LI' => 'Liechtenstein',
                        'LT' => 'Lithuania',
                        'LU' => 'Luxembourg',
                        'MK' => 'Macedonia',
                        'MT' => 'Malta',
                        'MD' => 'Moldova',
                        'MC' => 'Monaco',
                        'ME' => 'Montenegro',
                        'NL' => 'Netherlands',
                        'NO' => 'Norway',
                        'PL' => 'Poland',
                        'PT' => 'Portugal',
                        'RO' => 'Romania',
                        'RU' => 'Russian Federation',
                        'SM' => 'San Marino',
                        'RS' => 'Serbia',
                        'SK' => 'Slovakia',
                        'SI' => 'Slovenia',
                        'ES' => 'Spain',
                        'SJ' => 'Svalbard and Jan Mayen',
                        'SE' => 'Sweden',
                        'CH' => 'Switzerland',
                        'UA' => 'Ukraine',
                        'GB' => 'United Kingdom'
                    ],
                    'North America' => [
                        'AI' => 'Anguilla',
                        'AG' => 'Antigua and Barbuda',
                        'AW' => 'Aruba',
                        'BS' => 'Bahamas',
                        'BB' => 'Barbados',
                        'BL' => 'Saint Barthélemy',
                        'BZ' => 'Belize',
                        'BM' => 'Bermuda',
                        'CA' => 'Canada',
                        'KY' => 'Cayman Islands',
                        'CR' => 'Costa Rica',
                        'CU' => 'Cuba',
                        'DM' => 'Dominica',
                        'DO' => 'Dominican Republic',
                        'SV' => 'El Salvador',
                        'GL' => 'Greenland',
                        'GD' => 'Grenada',
                        'GP' => 'Guadeloupe',
                        'GT' => 'Guatemala',
                        'HT' => 'Haiti',
                        'HN' => 'Honduras',
                        'JM' => 'Jamaica',
                        'MF' => 'Saint-Martin (French part)',
                        'MQ' => 'Martinique',
                        'MX' => 'Mexico',
                        'MS' => 'Montserrat',
                        'AN' => 'Netherlands Antilles',
                        'NI' => 'Nicaragua',
                        'PA' => 'Panama',
                        'PR' => 'Puerto Rico',
                        'KN' => 'Saint Kitts and Nevis',
                        'LC' => 'Saint Lucia',
                        'PM' => 'Saint Pierre and Miquelon',
                        'VC' => 'Saint Vincent and The Grenadines',
                        'TT' => 'Trinidad and Tobago',
                        'TC' => 'Turks and Caicos Islands',
                        'US' => 'United States',
                        'VG' => 'Virgin Islands, British',
                        'VI' => 'Virgin Islands, U.S.'
                    ],
                    'Oceania' => [
                        'AS' => 'American Samoa',
                        'AU' => 'Australia',
                        'CK' => 'Cook Islands',
                        'FJ' => 'Fiji',
                        'PF' => 'French Polynesia',
                        'GU' => 'Guam',
                        'KI' => 'Kiribati',
                        'MH' => 'Marshall Islands',
                        'FM' => 'Micronesia',
                        'NR' => 'Nauru',
                        'NC' => 'New Caledonia',
                        'NZ' => 'New Zealand',
                        'NU' => 'Niue',
                        'NF' => 'Norfolk Island',
                        'MP' => 'Northern Mariana Islands',
                        'PW' => 'Palau',
                        'PG' => 'Papua New Guinea',
                        'PN' => 'Pitcairn',
                        'WS' => 'Samoa',
                        'SB' => 'Solomon Islands',
                        'TK' => 'Tokelau',
                        'TO' => 'Tonga',
                        'TV' => 'Tuvalu',
                        'UM' => 'United States Minor Outlying Islands',
                        'VU' => 'Vanuatu',
                        'WF' => 'Wallis and Futuna'
                    ],
                    'South America' => [
                        'AR' => 'Argentina',
                        'BO' => 'Bolivia',
                        'BR' => 'Brazil',
                        'CL' => 'Chile',
                        'CO' => 'Colombia',
                        'EC' => 'Ecuador',
                        'FK' => 'Falkland Islands (Malvinas]',
                        'GF' => 'French Guiana',
                        'GY' => 'Guyana',
                        'PY' => 'Paraguay',
                        'PE' => 'Peru',
                        'SR' => 'Suriname',
                        'UY' => 'Uruguay',
                        'VE' => 'Venezuela'
                    ]
            ];

        } elseif ($type == 3) {
            return ['Africa' => [
                        'DZA' => 'Algeria',
                        'AGO' => 'Angola',
                        'BEN' => 'Benin',
                        'BWA' => 'Botswana',
                        'BFA' => 'Burkina Faso',
                        'BDI' => 'Burundi',
                        'CMR' => 'Cameroon',
                        'CPV' => 'Cape Verde',
                        'CAF' => 'Central African Republic',
                        'TCD' => 'Chad',
                        'COM' => 'Comoros',
                        'COG' => 'Congo',
                        'COD' => 'The Democratic Republic of The Congo',
                        'CIV' => "Cote D'ivoire",
                        'DJI' => 'Djibouti',
                        'EGY' => 'Egypt',
                        'GNQ' => 'Equatorial Guinea',
                        'ERI' => 'Eritrea',
                        'ETH' => 'Ethiopia',
                        'GAB' => 'Gabon',
                        'GMB' => 'Gambia',
                        'GHA' => 'Ghana',
                        'GIN' => 'Guinea',
                        'GNB' => 'Guinea-bissau',
                        'KEN' => 'Kenya',
                        'LSO' => 'Lesotho',
                        'LBR' => 'Liberia',
                        'LBY' => 'Libya',
                        'MDG' => 'Madagascar',
                        'MWI' => 'Malawi',
                        'MLI' => 'Mali',
                        'MRT' => 'Mauritania',
                        'MUS' => 'Mauritius',
                        'MYT' => 'Mayotte',
                        'MAR' => 'Morocco',
                        'MOZ' => 'Mozambique',
                        'NAM' => 'Namibia',
                        'NER' => 'Niger',
                        'NGA' => 'Nigeria',
                        'REU' => 'Reunion',
                        'RWA' => 'Rwanda',
                        'SHN' => 'Saint Helena',
                        'STP' => 'Sao Tome and Principe',
                        'SEN' => 'Senegal',
                        'SYC' => 'Seychelles',
                        'SLE' => 'Sierra Leone',
                        'SOM' => 'Somalia',
                        'ZAF' => 'South Africa',
                        'SDN' => 'Sudan',
                        'SSD' => 'South Sudan',
                        'SWZ' => 'Swaziland',
                        'TZA' => 'Tanzania',
                        'TGO' => 'Togo',
                        'TUN' => 'Tunisia',
                        'UGA' => 'Uganda',
                        'ESH' => 'Western Sahara',
                        'ZMB' => 'Zambia',
                        'ZWE' => 'Zimbabwe'
                    ],
                    'Antarctica' => [
                        'ATA' => 'Antarctica',
                        'BVT' => 'Bouvet Island',
                        'ATF' => 'French Southern Territories',
                        'HMD' => 'Heard Island and Mcdonald Islands',
                        'SGS' => 'South Georgia and The South Sandwich Islands'
                    ],
                    'Asia' => [
                        'AFG' => 'Afghanistan',
                        'ARM' => 'Armenia',
                        'AZE' => 'Azerbaijan',
                        'BHR' => 'Bahrain',
                        'BGD' => 'Bangladesh',
                        'BTN' => 'Bhutan',
                        'IOT' => 'British Indian Ocean Territory',
                        'BRN' => 'Brunei Darussalam',
                        'KHM' => 'Cambodia',
                        'CHN' => 'China',
                        'CXR' => 'Christmas Island',
                        'CCK' => 'Cocos (Keeling] Islands',
                        'CYP' => 'Cyprus',
                        'GEO' => 'Georgia',
                        'HKG' => 'Hong Kong',
                        'IND' => 'India',
                        'IDN' => 'Indonesia',
                        'IRN' => 'Iran',
                        'IRQ' => 'Iraq',
                        'ISR' => 'Israel',
                        'JPN' => 'Japan',
                        'JOR' => 'Jordan',
                        'KAZ' => 'Kazakhstan',
                        'PRK' => "Democratic People's Republic of Korea",
                        'KOR' => 'Republic of Korea',
                        'KWT' => 'Kuwait',
                        'KGZ' => 'Kyrgyzstan',
                        'LAO' => "Lao People's Democratic Republic",
                        'LBN' => 'Lebanon',
                        'MAC' => 'Macao',
                        'MYS' => 'Malaysia',
                        'MDV' => 'Maldives',
                        'MNG' => 'Mongolia',
                        'MMR' => 'Myanmar',
                        'NPL' => 'Nepal',
                        'OMN' => 'Oman',
                        'PAK' => 'Pakistan',
                        'PSE' => 'Palestinia',
                        'PHL' => 'Philippines',
                        'QAT' => 'Qatar',
                        'SAU' => 'Saudi Arabia',
                        'SGP' => 'Singapore',
                        'LKA' => 'Sri Lanka',
                        'SYR' => 'Syrian Arab Republic',
                        'TWN' => 'Taiwan',
                        'TJK' => 'Tajikistan',
                        'THA' => 'Thailand',
                        'TLS' => 'Timor-leste',
                        'TUR' => 'Turkey',
                        'TKM' => 'Turkmenistan',
                        'ARE' => 'United Arab Emirates',
                        'UZB' => 'Uzbekistan',
                        'VNM' => 'Viet Nam',
                        'YEM' => 'Yemen'
                    ],
                    'Europe' => [
                        'ALA' => 'Åland Islands',
                        'ALB' => 'Albania',
                        'AND' => 'Andorra',
                        'AUT' => 'Austria',
                        'BLR' => 'Belarus',
                        'BEL' => 'Belgium',
                        'BIH' => 'Bosnia and Herzegovina',
                        'BGR' => 'Bulgaria',
                        'HRV' => 'Croatia',
                        'CZE' => 'Czech Republic',
                        'DNK' => 'Denmark',
                        'EST' => 'Estonia',
                        'FRO' => 'Faroe Islands',
                        'FIN' => 'Finland',
                        'FRA' => 'France',
                        'DEU' => 'Germany',
                        'GIB' => 'Gibraltar',
                        'GRC' => 'Greece',
                        'GGY' => 'Guernsey',
                        'VAT' => 'Holy See (Vatican City State]',
                        'HUN' => 'Hungary',
                        'ISL' => 'Iceland',
                        'IRL' => 'Ireland',
                        'IMN' => 'Isle of Man',
                        'ITA' => 'Italy',
                        'JEY' => 'Jersey',
                        'LVA' => 'Latvia',
                        'LIE' => 'Liechtenstein',
                        'LTU' => 'Lithuania',
                        'LUX' => 'Luxembourg',
                        'MKD' => 'Macedonia',
                        'MLT' => 'Malta',
                        'MDA' => 'Moldova',
                        'MCO' => 'Monaco',
                        'MNE' => 'Montenegro',
                        'NLD' => 'Netherlands',
                        'NOR' => 'Norway',
                        'POL' => 'Poland',
                        'PRT' => 'Portugal',
                        'ROU' => 'Romania',
                        'RUS' => 'Russian Federation',
                        'SMR' => 'San Marino',
                        'SRB' => 'Serbia',
                        'SVK' => 'Slovakia',
                        'SVN' => 'Slovenia',
                        'ESP' => 'Spain',
                        'SJM' => 'Svalbard and Jan Mayen',
                        'SWE' => 'Sweden',
                        'CHE' => 'Switzerland',
                        'UKR' => 'Ukraine',
                        'GBR' => 'United Kingdom'
                    ],
                    'North America' => [
                        'AIA' => 'Anguilla',
                        'ATG' => 'Antigua and Barbuda',
                        'ABW' => 'Aruba',
                        'BHS' => 'Bahamas',
                        'BRB' => 'Barbados',
                        'BLM' => 'Saint Barthélemy',
                        'BLZ' => 'Belize',
                        'BMU' => 'Bermuda',
                        'CAN' => 'Canada',
                        'CYM' => 'Cayman Islands',
                        'CRI' => 'Costa Rica',
                        'CUB' => 'Cuba',
                        'DMA' => 'Dominica',
                        'DOM' => 'Dominican Republic',
                        'SLV' => 'El Salvador',
                        'GRL' => 'Greenland',
                        'GRD' => 'Grenada',
                        'GLP' => 'Guadeloupe',
                        'GTM' => 'Guatemala',
                        'HTI' => 'Haiti',
                        'HND' => 'Honduras',
                        'JAM' => 'Jamaica',
                        'MAF' => 'Saint-Martin (French part)',
                        'MTQ' => 'Martinique',
                        'MEX' => 'Mexico',
                        'MSR' => 'Montserrat',
                        'ANT' => 'Netherlands Antilles',
                        'NIC' => 'Nicaragua',
                        'PAN' => 'Panama',
                        'PRI' => 'Puerto Rico',
                        'KNA' => 'Saint Kitts and Nevis',
                        'LCA' => 'Saint Lucia',
                        'SPM' => 'Saint Pierre and Miquelon',
                        'VCT' => 'Saint Vincent and The Grenadines',
                        'TTO' => 'Trinidad and Tobago',
                        'TCA' => 'Turks and Caicos Islands',
                        'USA' => 'United States',
                        'VGB' => 'Virgin Islands, British',
                        'VIR' => 'Virgin Islands, U.S.'
                    ],
                    'Oceania' => [
                        'ASM' => 'American Samoa',
                        'AUS' => 'Australia',
                        'COK' => 'Cook Islands',
                        'FJI' => 'Fiji',
                        'PYF' => 'French Polynesia',
                        'GUM' => 'Guam',
                        'KIR' => 'Kiribati',
                        'MHL' => 'Marshall Islands',
                        'FSM' => 'Micronesia',
                        'NRU' => 'Nauru',
                        'NCL' => 'New Caledonia',
                        'NZL' => 'New Zealand',
                        'NIU' => 'Niue',
                        'NFK' => 'Norfolk Island',
                        'MNP' => 'Northern Mariana Islands',
                        'PLW' => 'Palau',
                        'PNG' => 'Papua New Guinea',
                        'PCN' => 'Pitcairn',
                        'WSM' => 'Samoa',
                        'SLB' => 'Solomon Islands',
                        'TKL' => 'Tokelau',
                        'TON' => 'Tonga',
                        'TUV' => 'Tuvalu',
                        'UMI' => 'United States Minor Outlying Islands',
                        'VUT' => 'Vanuatu',
                        'WLF' => 'Wallis and Futuna'
                    ],
                    'South America' => [
                        'ARG' => 'Argentina',
                        'BOL' => 'Bolivia',
                        'BRA' => 'Brazil',
                        'CHL' => 'Chile',
                        'COL' => 'Colombia',
                        'ECU' => 'Ecuador',
                        'FLK' => 'Falkland Islands (Malvinas]',
                        'GUF' => 'French Guiana',
                        'GUY' => 'Guyana',
                        'PRY' => 'Paraguay',
                        'PER' => 'Peru',
                        'SUR' => 'Suriname',
                        'URY' => 'Uruguay',
                        'VEN' => 'Venezuela'
                    ]
            ];
        } else {
            return ['Africa' => [
                        '012' => 'Algeria',
                        '024' => 'Angola',
                        '204' => 'Benin',
                        '072' => 'Botswana',
                        '854' => 'Burkina Faso',
                        '108' => 'Burundi',
                        '120' => 'Cameroon',
                        '132' => 'Cape Verde',
                        '140' => 'Central African Republic',
                        '148' => 'Chad',
                        '174' => 'Comoros',
                        '178' => 'Congo',
                        '180' => 'The Democratic Republic of The Congo',
                        '384' => "Cote D'ivoire",
                        '262' => 'Djibouti',
                        '818' => 'Egypt',
                        '226' => 'Equatorial Guinea',
                        '232' => 'Eritrea',
                        '231' => 'Ethiopia',
                        '266' => 'Gabon',
                        '270' => 'Gambia',
                        '288' => 'Ghana',
                        '324' => 'Guinea',
                        '624' => 'Guinea-bissau',
                        '404' => 'Kenya',
                        '426' => 'Lesotho',
                        '430' => 'Liberia',
                        '434' => 'Libya',
                        '450' => 'Madagascar',
                        '454' => 'Malawi',
                        '466' => 'Mali',
                        '478' => 'Mauritania',
                        '480' => 'Mauritius',
                        '175' => 'Mayotte',
                        '504' => 'Morocco',
                        '508' => 'Mozambique',
                        '516' => 'Namibia',
                        '562' => 'Niger',
                        '566' => 'Nigeria',
                        '638' => 'Reunion',
                        '646' => 'Rwanda',
                        '654' => 'Saint Helena',
                        '678' => 'Sao Tome and Principe',
                        '686' => 'Senegal',
                        '690' => 'Seychelles',
                        '694' => 'Sierra Leone',
                        '706' => 'Somalia',
                        '710' => 'South Africa',
                        '736' => 'Sudan',
                        '728' => 'South Sudan',
                        '748' => 'Swaziland',
                        '834' => 'Tanzania',
                        '768' => 'Togo',
                        '788' => 'Tunisia',
                        '800' => 'Uganda',
                        '732' => 'Western Sahara',
                        '894' => 'Zambia',
                        '716' => 'Zimbabwe'
                    ],
                    'Antarctica' => [
                        '010' => 'Antarctica',
                        '074' => 'Bouvet Island',
                        '260' => 'French Southern Territories',
                        '334' => 'Heard Island and Mcdonald Islands',
                        '239' => 'South Georgia and The South Sandwich Islands'
                    ],
                    'Asia' => [
                        '004' => 'Afghanistan',
                        '051' => 'Armenia',
                        '031' => 'Azerbaijan',
                        '048' => 'Bahrain',
                        '050' => 'Bangladesh',
                        '064' => 'Bhutan',
                        '086' => 'British Indian Ocean Territory',
                        '096' => 'Brunei Darussalam',
                        '116' => 'Cambodia',
                        '156' => 'China',
                        '162' => 'Christmas Island',
                        '166' => 'Cocos (Keeling] Islands',
                        '196' => 'Cyprus',
                        '268' => 'Georgia',
                        '344' => 'Hong Kong',
                        '356' => 'India',
                        '360' => 'Indonesia',
                        '364' => 'Iran',
                        '368' => 'Iraq',
                        '376' => 'Israel',
                        '392' => 'Japan',
                        '400' => 'Jordan',
                        '398' => 'Kazakhstan',
                        '408' => "Democratic People's Republic of Korea",
                        '410' => 'Republic of Korea',
                        '414' => 'Kuwait',
                        '417' => 'Kyrgyzstan',
                        '418' => "Lao People's Democratic Republic",
                        '422' => 'Lebanon',
                        '446' => 'Macao',
                        '458' => 'Malaysia',
                        '462' => 'Maldives',
                        '496' => 'Mongolia',
                        '104' => 'Myanmar',
                        '524' => 'Nepal',
                        '512' => 'Oman',
                        '586' => 'Pakistan',
                        '275' => 'Palestinia',
                        '608' => 'Philippines',
                        '634' => 'Qatar',
                        '682' => 'Saudi Arabia',
                        '702' => 'Singapore',
                        '144' => 'Sri Lanka',
                        '760' => 'Syrian Arab Republic',
                        '158' => 'Taiwan',
                        '762' => 'Tajikistan',
                        '764' => 'Thailand',
                        '626' => 'Timor-leste',
                        '792' => 'Turkey',
                        '795' => 'Turkmenistan',
                        '784' => 'United Arab Emirates',
                        '860' => 'Uzbekistan',
                        '704' => 'Viet Nam',
                        '887' => 'Yemen'
                    ],
                    'Europe' => [
                        '248' => 'Åland Islands',
                        '008' => 'Albania',
                        '020' => 'Andorra',
                        '040' => 'Austria',
                        '112' => 'Belarus',
                        '056' => 'Belgium',
                        '070' => 'Bosnia and Herzegovina',
                        '100' => 'Bulgaria',
                        '191' => 'Croatia',
                        '203' => 'Czech Republic',
                        '208' => 'Denmark',
                        '233' => 'Estonia',
                        '234' => 'Faroe Islands',
                        '246' => 'Finland',
                        '250' => 'France',
                        '276' => 'Germany',
                        '292' => 'Gibraltar',
                        '300' => 'Greece',
                        '831' => 'Guernsey',
                        '336' => 'Holy See (Vatican City State]',
                        '348' => 'Hungary',
                        '352' => 'Iceland',
                        '372' => 'Ireland',
                        '833' => 'Isle of Man',
                        '380' => 'Italy',
                        '832' => 'Jersey',
                        '428' => 'Latvia',
                        '438' => 'Liechtenstein',
                        '440' => 'Lithuania',
                        '442' => 'Luxembourg',
                        '807' => 'Macedonia',
                        '470' => 'Malta',
                        '498' => 'Moldova',
                        '492' => 'Monaco',
                        '499' => 'Montenegro',
                        '528' => 'Netherlands',
                        '578' => 'Norway',
                        '616' => 'Poland',
                        '620' => 'Portugal',
                        '642' => 'Romania',
                        '643' => 'Russian Federation',
                        '674' => 'San Marino',
                        '688' => 'Serbia',
                        '703' => 'Slovakia',
                        '705' => 'Slovenia',
                        '724' => 'Spain',
                        '744' => 'Svalbard and Jan Mayen',
                        '752' => 'Sweden',
                        '756' => 'Switzerland',
                        '804' => 'Ukraine',
                        '826' => 'United Kingdom'
                    ],
                    'North America' => [
                        '660' => 'Anguilla',
                        '028' => 'Antigua and Barbuda',
                        '533' => 'Aruba',
                        '044' => 'Bahamas',
                        '052' => 'Barbados',
                        '652' => 'Saint Barthélemy',
                        '084' => 'Belize',
                        '060' => 'Bermuda',
                        '124' => 'Canada',
                        '136' => 'Cayman Islands',
                        '188' => 'Costa Rica',
                        '192' => 'Cuba',
                        '212' => 'Dominica',
                        '214' => 'Dominican Republic',
                        '222' => 'El Salvador',
                        '304' => 'Greenland',
                        '308' => 'Grenada',
                        '312' => 'Guadeloupe',
                        '320' => 'Guatemala',
                        '332' => 'Haiti',
                        '340' => 'Honduras',
                        '388' => 'Jamaica',
                        '663' => 'Saint-Martin (French part)',
                        '474' => 'Martinique',
                        '484' => 'Mexico',
                        '500' => 'Montserrat',
                        '530' => 'Netherlands Antilles',
                        '558' => 'Nicaragua',
                        '591' => 'Panama',
                        '630' => 'Puerto Rico',
                        '659' => 'Saint Kitts and Nevis',
                        '662' => 'Saint Lucia',
                        '666' => 'Saint Pierre and Miquelon',
                        '670' => 'Saint Vincent and The Grenadines',
                        '780' => 'Trinidad and Tobago',
                        '796' => 'Turks and Caicos Islands',
                        '840' => 'United States',
                        '092' => 'Virgin Islands, British',
                        '850' => 'Virgin Islands, U.S.'
                    ],
                    'Oceania' => [
                        '016' => 'American Samoa',
                        '036' => 'Australia',
                        '184' => 'Cook Islands',
                        '242' => 'Fiji',
                        '258' => 'French Polynesia',
                        '316' => 'Guam',
                        '296' => 'Kiribati',
                        '584' => 'Marshall Islands',
                        '583' => 'Micronesia',
                        '520' => 'Nauru',
                        '540' => 'New Caledonia',
                        '554' => 'New Zealand',
                        '570' => 'Niue',
                        '574' => 'Norfolk Island',
                        '580' => 'Northern Mariana Islands',
                        '585' => 'Palau',
                        '598' => 'Papua New Guinea',
                        '612' => 'Pitcairn',
                        '882' => 'Samoa',
                        '090' => 'Solomon Islands',
                        '772' => 'Tokelau',
                        '776' => 'Tonga',
                        '798' => 'Tuvalu',
                        '581' => 'United States Minor Outlying Islands',
                        '548' => 'Vanuatu',
                        '876' => 'Wallis and Futuna'
                    ],
                    'South America' => [
                        '032' => 'Argentina',
                        '068' => 'Bolivia',
                        '076' => 'Brazil',
                        '152' => 'Chile',
                        '170' => 'Colombia',
                        '218' => 'Ecuador',
                        '238' => 'Falkland Islands (Malvinas]',
                        '254' => 'French Guiana',
                        '328' => 'Guyana',
                        '600' => 'Paraguay',
                        '604' => 'Peru',
                        '740' => 'Suriname',
                        '858' => 'Uruguay',
                        '862' => 'Venezuela'
                    ]
            ];
        }
    }

    /**
     * @param Int     $from
     * @param Int     $to
     * @param String  $code
     * @return Array|String
     */
    public static function convertCode(int $from, int $to, string $code): array
    {
        $items = $this->listByUNCode();
        $items_new = [];
        foreach ($items as $item) {
            if (
                $from == 2
                && $to == 3
            ) {
                $items_new = array_merge($items_new, [$item[0] => $item[1]]);
            } elseif (
                $from == 3
                && $to == 2
            ) {
                $items_new = array_merge($items_new, [$item[1] => $item[0]]);
            } else {
                throw new InvalidArgumentException([$from, $to]);
            }
        }

        if (isset($items_new[$code])) {
            return $items_new[$$code];
        } else {
            throw new InvalidArgumentException($to);
        }
    }

    /**
     * @param Int  $type
     * @return Array
     */
    public static function listByUNCode($type = null): array
    {
        $items = [
            '004' => ['AF', 'AFG'],
            '008' => ['AL', 'ALB'],
            '010' => ['AQ', 'ATA'],
            '012' => ['DZ', 'DZA'],
            '016' => ['AS', 'ASM'],
            '020' => ['AD', 'AND'],
            '024' => ['AO', 'AGO'],
            '028' => ['AG', 'ATG'],
            '031' => ['AZ', 'AZE'],
            '032' => ['AR', 'ARG'],
            '036' => ['AU', 'AUS'],
            '040' => ['AT', 'AUT'],
            '044' => ['BS', 'BHS'],
            '048' => ['BH', 'BHR'],
            '050' => ['BD', 'BGD'],
            '051' => ['AM', 'ARM'],
            '052' => ['BB', 'BRB'],
            '056' => ['BE', 'BEL'],
            '060' => ['BM', 'BMU'],
            '064' => ['BT', 'BTN'],
            '068' => ['BO', 'BOL'],
            '070' => ['BA', 'BIH'],
            '072' => ['BW', 'BWA'],
            '074' => ['BV', 'BVT'],
            '076' => ['BR', 'BRA'],
            '084' => ['BZ', 'BLZ'],
            '086' => ['IO', 'IOT'],
            '090' => ['SB', 'SLB'],
            '092' => ['VG', 'VGB'],
            '096' => ['BN', 'BRN'],
            '100' => ['BG', 'BGR'],
            '104' => ['MM', 'MMR'],
            '108' => ['BI', 'BDI'],
            '112' => ['BY', 'BLR'],
            '116' => ['KH', 'KHM'],
            '120' => ['CM', 'CMR'],
            '124' => ['CA', 'CAN'],
            '132' => ['CV', 'CPV'],
            '136' => ['KY', 'CYM'],
            '140' => ['CF', 'CAF'],
            '144' => ['LK', 'LKA'],
            '148' => ['TD', 'TCD'],
            '152' => ['CL', 'CHL'],
            '156' => ['CN', 'CHN'],
            '158' => ['TW', 'TWN'],
            '162' => ['CX', 'CXR'],
            '166' => ['CC', 'CCK'],
            '170' => ['CO', 'COL'],
            '174' => ['KM', 'COM'],
            '175' => ['YT', 'MYT'],
            '178' => ['CG', 'COG'],
            '180' => ['CD', 'COD'],
            '184' => ['CK', 'COK'],
            '188' => ['CR', 'CRI'],
            '191' => ['HR', 'HRV'],
            '192' => ['CU', 'CUB'],
            '196' => ['CY', 'CYP'],
            '203' => ['CZ', 'CZE'],
            '204' => ['BJ', 'BEN'],
            '208' => ['DK', 'DNK'],
            '212' => ['DM', 'DMA'],
            '214' => ['DO', 'DOM'],
            '218' => ['EC', 'ECU'],
            '222' => ['SV', 'SLV'],
            '226' => ['GQ', 'GNQ'],
            '231' => ['ET', 'ETH'],
            '232' => ['ER', 'ERI'],
            '233' => ['EE', 'EST'],
            '234' => ['FO', 'FRO'],
            '238' => ['FK', 'FLK'],
            '239' => ['GS', 'SGS'],
            '242' => ['FJ', 'FJI'],
            '246' => ['FI', 'FIN'],
            '248' => ['AX', 'ALA'],
            '250' => ['FR', 'FRA'],
            '254' => ['GF', 'GUF'],
            '258' => ['PF', 'PYF'],
            '260' => ['TF', 'ATF'],
            '262' => ['DJ', 'DJI'],
            '266' => ['GA', 'GAB'],
            '268' => ['GE', 'GEO'],
            '270' => ['GM', 'GMB'],
            '275' => ['PS', 'PSE'],
            '276' => ['DE', 'DEU'],
            '288' => ['GH', 'GHA'],
            '292' => ['GI', 'GIB'],
            '296' => ['KI', 'KIR'],
            '300' => ['GR', 'GRC'],
            '304' => ['GL', 'GRL'],
            '308' => ['GD', 'GRD'],
            '312' => ['GP', 'GLP'],
            '316' => ['GU', 'GUM'],
            '320' => ['GT', 'GTM'],
            '324' => ['GN', 'GIN'],
            '328' => ['GY', 'GUY'],
            '332' => ['HT', 'HTI'],
            '334' => ['HM', 'HMD'],
            '336' => ['VA', 'VAT'],
            '340' => ['HN', 'HND'],
            '344' => ['HK', 'HKG'],
            '348' => ['HU', 'HUN'],
            '352' => ['IS', 'ISL'],
            '356' => ['IN', 'IND'],
            '360' => ['ID', 'IDN'],
            '364' => ['IR', 'IRN'],
            '368' => ['IQ', 'IRQ'],
            '372' => ['IE', 'IRL'],
            '376' => ['IL', 'ISR'],
            '380' => ['IT', 'ITA'],
            '384' => ['CI', 'CIV'],
            '388' => ['JM', 'JAM'],
            '392' => ['JP', 'JPN'],
            '398' => ['KZ', 'KAZ'],
            '400' => ['JO', 'JOR'],
            '404' => ['KE', 'KEN'],
            '408' => ['KP', 'PRK'],
            '410' => ['KR', 'KOR'],
            '414' => ['KW', 'KWT'],
            '417' => ['KG', 'KGZ'],
            '418' => ['LA', 'LAO'],
            '422' => ['LB', 'LBN'],
            '426' => ['LS', 'LSO'],
            '428' => ['LV', 'LVA'],
            '430' => ['LR', 'LBR'],
            '434' => ['LY', 'LBY'],
            '438' => ['LI', 'LIE'],
            '440' => ['LT', 'LTU'],
            '442' => ['LU', 'LUX'],
            '446' => ['MO', 'MAC'],
            '450' => ['MG', 'MDG'],
            '454' => ['MW', 'MWI'],
            '458' => ['MY', 'MYS'],
            '462' => ['MV', 'MDV'],
            '466' => ['ML', 'MLI'],
            '470' => ['MT', 'MLT'],
            '474' => ['MQ', 'MTQ'],
            '478' => ['MR', 'MRT'],
            '480' => ['MU', 'MUS'],
            '484' => ['MX', 'MEX'],
            '492' => ['MC', 'MCO'],
            '496' => ['MN', 'MNG'],
            '498' => ['MD', 'MDA'],
            '499' => ['ME', 'MNE'],
            '500' => ['MS', 'MSR'],
            '504' => ['MA', 'MAR'],
            '508' => ['MZ', 'MOZ'],
            '512' => ['OM', 'OMN'],
            '516' => ['NA', 'NAM'],
            '520' => ['NR', 'NRU'],
            '524' => ['NP', 'NPL'],
            '528' => ['NL', 'NLD'],
            '530' => ['AN', 'ANT'],
            '533' => ['AW', 'ABW'],
            '540' => ['NC', 'NCL'],
            '548' => ['VU', 'VUT'],
            '554' => ['NZ', 'NZL'],
            '558' => ['NI', 'NIC'],
            '562' => ['NE', 'NER'],
            '566' => ['NG', 'NGA'],
            '570' => ['NU', 'NIU'],
            '574' => ['NF', 'NFK'],
            '578' => ['NO', 'NOR'],
            '580' => ['MP', 'MNP'],
            '581' => ['UM', 'UMI'],
            '583' => ['FM', 'FSM'],
            '584' => ['MH', 'MHL'],
            '585' => ['PW', 'PLW'],
            '586' => ['PK', 'PAK'],
            '591' => ['PA', 'PAN'],
            '598' => ['PG', 'PNG'],
            '600' => ['PY', 'PRY'],
            '604' => ['PE', 'PER'],
            '608' => ['PH', 'PHL'],
            '612' => ['PN', 'PCN'],
            '616' => ['PL', 'POL'],
            '620' => ['PT', 'PRT'],
            '624' => ['GW', 'GNB'],
            '626' => ['TL', 'TLS'],
            '630' => ['PR', 'PRI'],
            '634' => ['QA', 'QAT'],
            '638' => ['RE', 'REU'],
            '642' => ['RO', 'ROU'],
            '643' => ['RU', 'RUS'],
            '646' => ['RW', 'RWA'],
            '652' => ['BL', 'BLM'],
            '654' => ['SH', 'SHN'],
            '659' => ['KN', 'KNA'],
            '660' => ['AI', 'AIA'],
            '662' => ['LC', 'LCA'],
            '663' => ['MF', 'MAF'],
            '666' => ['PM', 'SPM'],
            '670' => ['VC', 'VCT'],
            '674' => ['SM', 'SMR'],
            '678' => ['ST', 'STP'],
            '682' => ['SA', 'SAU'],
            '686' => ['SN', 'SEN'],
            '688' => ['RS', 'SRB'],
            '690' => ['SC', 'SYC'],
            '694' => ['SL', 'SLE'],
            '702' => ['SG', 'SGP'],
            '703' => ['SK', 'SVK'],
            '704' => ['VN', 'VNM'],
            '705' => ['SI', 'SVN'],
            '706' => ['SO', 'SOM'],
            '710' => ['ZA', 'ZAF'],
            '716' => ['ZW', 'ZWE'],
            '724' => ['ES', 'ESP'],
            '728' => ['SS', 'SSD'],
            '732' => ['EH', 'ESH'],
            '736' => ['SD', 'SDN'],
            '740' => ['SR', 'SUR'],
            '744' => ['SJ', 'SJM'],
            '748' => ['SZ', 'SWZ'],
            '752' => ['SE', 'SWE'],
            '756' => ['CH', 'CHE'],
            '760' => ['SY', 'SYR'],
            '762' => ['TJ', 'TJK'],
            '764' => ['TH', 'THA'],
            '768' => ['TG', 'TGO'],
            '772' => ['TK', 'TKL'],
            '776' => ['TO', 'TON'],
            '780' => ['TT', 'TTO'],
            '784' => ['AE', 'ARE'],
            '788' => ['TN', 'TUN'],
            '792' => ['TR', 'TUR'],
            '795' => ['TM', 'TKM'],
            '796' => ['TC', 'TCA'],
            '798' => ['TV', 'TUV'],
            '800' => ['UG', 'UGA'],
            '804' => ['UA', 'UKR'],
            '807' => ['MK', 'MKD'],
            '818' => ['EG', 'EGY'],
            '826' => ['GB', 'GBR'],
            '831' => ['GG', 'GGY'],
            '832' => ['JE', 'JEY'],
            '833' => ['IM', 'IMN'],
            '834' => ['TZ', 'TZA'],
            '840' => ['US', 'USA'],
            '850' => ['VI', 'VIR'],
            '854' => ['BF', 'BFA'],
            '858' => ['UY', 'URY'],
            '860' => ['UZ', 'UZB'],
            '862' => ['VE', 'VEN'],
            '876' => ['WF', 'WLF'],
            '882' => ['WS', 'WSM'],
            '887' => ['YE', 'YEM'],
            '894' => ['ZM', 'ZMB']
        ];

        if (is_null($type)) {
            return $items;
        } elseif ($type == 2) {
            $items_new = [];
            foreach ($items as $key => $item) {
                $items_new = array_merge($items_new, [$key => $item[0]]);
            }
        } elseif ($type == 3) {
            $items_new = [];
            foreach ($items as $key => $item) {
                $items_new = array_merge($items_new, [$key => $item[1]]);
            }
        }

        return $items_new;
    }
}
